### ISSUE TITLE
Proposal: A dedicated section for security bugs in contribution guideline

### ISSUE THREAD

**Issue by donutloop** [ExperienceOne/apikit#1]
In my point of view! It might be dangerous to expose any security issues on Github in any form. It will be better if you clarify such problems over email.

Doc example:

## I have found a security bug!
Please contact Sebastian Loose via email (sebastian.loose@experienceone.com) 

Sebastian needs:

- Description of the security issue
- Attack vectors
- Fix

What do you think?

**Comment by cybernop** [comment]
Sounds good to me. Would there be a dedicated distribution list?

**Comment by seseloos** [comment]
Good point. I think providing a mailing list for that would be the best solution. We should talk about that internal at EO in the next days and provide the needed things.

**Comment by donutloop** [comment]
@seseloos Any progress?

**Comment by seseloos** [comment]
@donutloop sorry for the late response. I will update the contribution guideline at the end of the week.

**Comment by donutloop** [comment]
@seseloos  sounds good to me

**Comment by seseloos** [comment]
@donutloop added a section for security issues to the contribution guidelines. Thank you for pointing that out.

**Comment by donutloop** [comment]
> @donutloop added a section for security issues to the contribution guidelines. Thank you for pointing that out.

Cool! :)
