### ISSUE TITLE
[CI/CD] Setup Github Test Action

### ISSUE THREAD

**Issue by donutloop** [ExperienceOne/apikit#22]
we should set up a Github test action, to minimize the risk of pushing a broken commit to the master branch.

Ref: https://github.com/features/actions

**Comment by donutloop** [comment]
@seseloos

**Comment by seseloos** [comment]
Added a GitHub Action that runs golangci-lint and the tests (#26)

**Comment by donutloop** [comment]
@seseloos 👍
